#ifndef __BLOCKDEV_H__
#define	__BLOCKDEV_H__

enum BlockdevStatus {
	BLOCKDEV_STATUS_NOSIZE = -6,
	BLOCKDEV_STATUS_NOAVAIL = -5,
	BLOCKDEV_STATUS_ARGLEN = -4,
	BLOCKDEV_STATUS_READONLY = -3,
	BLOCKDEV_STATUS_RANGE = -2,
	BLOCKDEV_STATUS_BAD_DEV = -1,
	BLOCKDEV_STATUS_OK	= 0,
};

#endif
